version: "3.4"
services:
    database:
        image: postgres
        environment:
            - "POSTGRES_PASSWORD=test"
        volumes:
            - ./postgresdata:/var/lib/postgresql/data

    webapp:
        build:
            context: "."
            dockerfile: "Dockerfile"
            target: production
        environment:
            - "ASPNETCORE_ENVIRONMENT=Production"
            - "MINITWIT_ENVIRONMENT=docker"
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - database
