version: "3.4"
services:
    traefik:
        image: traefik:v2.1
        # Enables the web UI and tells Traefik to listen to docker
        # @TODO: Secure traefik api/dashboard
        command:
            #- "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.http.address=:80"

            # HTTPS Config
            - "--entrypoints.https.address=:443"
            - "--certificatesresolvers.webappresolver.acme.tlschallenge=true"
            - "--certificatesresolvers.webappresolver.acme.email=joln@itu.dk"
            - "--certificatesresolvers.webappresolver.acme.storage=/letsencrypt/acme.json"
            # Use Let's encrypt staging server
            - "--certificatesresolvers.webappresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
        ports:
            # The HTTP port
            - "80:80"

            # The HTTPS port
            - "443:443"

            # The Web UI (enabled by --api.insecure=true)
            - "8080:8080"
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock:ro

            # So that Traefik can persist the HTTP certificate
            - ./letsencrypt:/letsencrypt

    webapp:
        build:
            context: "."
            dockerfile: "Dockerfile"
            target: production
        restart: unless-stopped
        environment:
            - "ASPNETCORE_ENVIRONMENT=Production"
            - "MINITWIT_ENVIRONMENT=docker"
            - "POSTGRES_CONNECTIONSTRING=Host=database;Database=MiniTwit;Username=postgres;Password=test"
        volumes:
            - ./aspnetkeys:/root/.aspnet/DataProtection-Keys
        labels:
            # Tell traefik that this container should be exposed to the public
            - "traefik.enable=true"
            # Tell traefik which port our container listens on
            - "traefik.http.services.webapp.loadbalancer.server.port=80"
            # Tell where the service should be available
            - "traefik.http.routers.webapp.rule=Host(`minitwit.tk`) || Path(`/{path:.*}`)"
            - "traefik.http.routers.webapp.entrypoints=http"
            # - "traefik.http.routers.webapp.tls.certresolver=webappresolver"
            # - "traefik.http.routers.webapp.middlewares=webappredirecthttp@docker"
            # Redirect http to https
            # - "traefik.http.middlewares.webappredirecthttp.redirectscheme.scheme=https"
            # - "traefik.http.middlewares.webappredirecthttp.redirectscheme.permanent=true"
        depends_on:
            - database

    database:
        image: postgres:12
        restart: unless-stopped
        environment:
            - "POSTGRES_PASSWORD=test"
        volumes:
            - ./postgresdata:/var/lib/postgresql/data