version: "3.4"
services:
    database:
        build: ./DatabaseDocker/
        ports:
            - "5432:5432"
    webapp:
        build:
            context: "."
            dockerfile: "Dockerfile"
            target: development
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "MINITWIT_ENVIRONMENT=docker"
        ports:
            - "5001:5001"
            - "5000:5000"
            - "80:80"
            - "443:443"
        volumes:
            - ./:/app
        depends_on:
            - database
