version: "3.4"

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
    webapp:
        build:
            context: "."
            dockerfile: "Dockerfile"
            target: development
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "MINITWIT_ENVIRONMENT=docker"
            - "POSTGRES_CONNECTIONSTRING=Host=database;Database=MiniTwit;Username=postgres;Password=test"
            - "ASPNETCORE_URLS=https://0.0.0.0:443"
        volumes:
            - ./:/app
            - ./aspnetkeys:/root/.aspnet/DataProtection-Keys
        depends_on:
            - database
            - prometheus
            - grafana
        ports:
            - "80:80"
            - "443:443"

    database:
        image: postgres:12
        environment:
            - "POSTGRES_PASSWORD=test"
        ports:
            - "5432:5432"
        volumes:
            - ./postgresdata:/var/lib/postgresql/data

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - "9090:9090"  
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus

    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"  
        volumes:
            - grafana_data:/var/lib/grafana
        depends_on: 
            - prometheus
