version: "3.4"
services:
    database:
        image: postgres
        environment:
            - "POSTGRES_PASSWORD=test"
        ports:
            - "5432:5432"
        volumes:
            - ./postgresdata:/var/lib/postgresql/data
    webapp:
        build:
            context: "."
            dockerfile: "Dockerfile"
            target: development
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "MINITWIT_ENVIRONMENT=docker"
            - "POSTGRES_CONNECTIONSTRING=Host=database;Database=MiniTwit;Username=postgres;Password=test"
        ports:
            - "5001:5001"
            - "5000:5000"
            - "80:80"
            - "443:443"
        volumes:
            - ./:/app
        depends_on:
            - database
