version: "3.4"
services:
    database:
        image: postgres:12
        restart: unless-stopped
        environment:
            - "POSTGRES_PASSWORD=test"
        volumes:
            - ./postgresdata:/var/lib/postgresql/data

    webapp:
        build:
            context: "."
            dockerfile: "Dockerfile"
            target: production
        restart: unless-stopped
        environment:
            - "ASPNETCORE_ENVIRONMENT=Production"
            - "MINITWIT_ENVIRONMENT=docker"
            - "POSTGRES_CONNECTIONSTRING=Host=database;Database=MiniTwit;Username=postgres;Password=test"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./aspnetkeys:/root/.aspnet/DataProtection-Keys
        depends_on:
            - database
