version: "3.4"

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
    
    webapp:
        build:
            context: "."
            dockerfile: "Dockerfile"
            target: production
            cache_from:
                - jlndk/devoops:latest
        image: jlndk/devoops:latest
        restart: unless-stopped
        environment:
            - "ASPNETCORE_ENVIRONMENT=Production"
            - "MINITWIT_ENVIRONMENT=docker"
            - "POSTGRES_CONNECTIONSTRING=Host=database;Database=MiniTwit;Username=postgres;Password=test"
        volumes:
            - ./aspnetkeys:/root/.aspnet/DataProtection-Keys
        depends_on:
            - database
            - prometheus
            - grafana

    database:
        image: postgres:12
        restart: unless-stopped
        environment:
            - "POSTGRES_PASSWORD=test"
        volumes:
            - ./postgresdata:/var/lib/postgresql/data

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - "9090:9090"  
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus

    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"  
        volumes:
            - grafana_data:/var/lib/grafana
        depends_on: 
            - prometheus
