name: Build, push and deploy on push to master

# on:
#     push:
#         branches:
#             - master
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Log into dockerhub
              run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            # Investigate Caching
            - name: Build with docker compose
              run: docker-compose -f docker-compose.prod.yml build
            - name: Push docker images to docker hub
              run: docker-compose -f docker-compose.prod.yml push
            - name: Configure deployment credentials
              uses: webfactory/ssh-agent@v0.2.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            # Deploy
            - name: Deploy on production
              run: docker-compose -H "ssh://root@${{ secrets.SSH_HOST }}" up -d
