name: Build, push and deploy on push to master

# on:
#     push:
#         branches:
#             - master
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Log into dockerhub
              run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            # Investigate Caching
            - name: Build with docker compose
              run: docker-compose -f docker-compose.prod.yml build
            - name: Push docker images to docker hub
              run: docker-compose -f docker-compose.prod.yml push
            - name: Configure deployment credentials
              uses: shimataro/ssh-key-action@v2
              with:
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                known_hosts: ${{ secrets.SSH_HOST }}
            # Deploy
            - name: Deploy to Production
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    cd devoops
                    git pull
                    ./deploy.sh