name: Build, push and deploy on push to master

# on:
#     push:
#         branches:
#             - master
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Log into dockerhub
              run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            # Investigate Caching
            - name: Build with docker compose
              run: docker-compose -f docker-compose.prod.yml build
            - name: Push docker images to docker hub
              run: docker-compose -f docker-compose.prod.yml push
            - name: Configure deployment credentials
              uses: shimataro/ssh-key-action@v2
              with:
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                known_hosts: ${{ secrets.SSH_HOST }}
            # Deploy
            - name: Deploy to Production
              uses: JorgenVatle/docker-compose-deploy@v1.0
              with:
                deploy_targets: '${{ secrets.SSH_HOST }}' # required, comma separated list of servers to deploy to.

                ssh_user: '${{ secrets.SSH_USERNAME }}' # optional, user to connect to deploy targets with. Defaults to 'root'
                compose_file: 'docker-compose.prod.yml' # optional, path/filename of your docker-compose file. Defaults to 'docker-compose.yml'
                #validate_container: 'devoops_webapp_1' # optional, validate that the given container name is running. Otherwise, throw an error. Defaults to 'app'   